apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z7fwj6cjy-go 
  janus-idp.io/tekton: z7fwj6cjy-go
  backstage.io/kubernetes-id: z7fwj6cjy-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z7fwj6cjy-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml